name = "lucidia-earth"
compatibility_date = "2025-12-23"

[env.production]
routes = [
  { pattern = "lucidia.earth", custom_domain = true },
  { pattern = "www.lucidia.earth", custom_domain = true }
]
